### ISSUE TITLE
architecture: DNS over TLS client authentication

### ISSUE THREAD

**Issue by oej** [ietf-wg-dance/draft-dance-architecture#7]
Anyone that can write text on this?

**Comment by oej** [comment]
Need a short text with ideas or we will just remove this for now.

**Comment by oej** [comment]
We'll mention this as a future use case in the current document and keep it in the backlog for later work.

**Comment by oej** [comment]
Interim accept mention

**Comment by bwoodcock** [comment]
Sorry, been swamped with other stuff.  Here's some text:

DNS-over-TLS client authentication is applicable to most portions of the transport segments of the DNS infrastructure. 

From authoritative to authoritative secondary, it can be applied to XFR-over-TLS ("XoT") as an upgrade to TSIG, removing the need for out-of-band communication of shared secrets, currently a weak point in that portion of the infrastructure.

From authoritative servers to recursive servers, in situations in which both are part of a common trust-group or have access to the same non-public or split-horizon zone data, client authentication allows authoritative servers to give selective access to specific recursive servers. Alternatively, some recursive servers could authenticate in order to gain access to non-content-related special services, such as a higher query rate-limit quota than is publicly available.

Between recursive resolvers and caching/forwarding or stub resolvers, authentication can be used to gain access to special services, such as subscription-based malware blocking, or visibility of corporate split-horizon internal zone, or to distinguish between subscribers to different performance tiers.

In the ideal implementation, client and server would bidirectionally authenticate, using DANE certificates to bootstrap TLS transport security.

**Comment by oej** [comment]
Thank you Bob! Maybe we could specific "DANE client certificates" in the last sentence to be more specific.
